### ISSUE TITLE
some issue in faq section 

### ISSUE THREAD

**Issue by RAHUL956777** [Git21221/IBMSkillsBuild#32]
![ss](https://github.com/Git21221/IBMSkillsBuild/assets/77888604/3475ffef-76e9-45f2-9c85-30cdaf5be099)

**Comment by Git21221** [comment]
@RAHUL956777 Go ahead and fix it. make a pr with proper screenshot

**Comment by RAHUL956777** [comment]
this issue was closed with this pr #35
