### ISSUE TITLE
Improve UI for Gallery cards

### ISSUE THREAD

**Issue by aanchal-fatwani** [Git21221/IBMSkillsBuild#33]
@Git21221  As part of HacktoberFest2023, I wish to update the UI of the Gallery cards for better presentation.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

![image](https://github.com/Git21221/IBMSkillsBuild/assets/63228776/7de0dafe-134a-495b-ab55-62730171fafe)

**Comment by Git21221** [comment]
Sure go ahead, @aanchal-fatwani , make sure to make a pr with proper screenshot
