### ISSUE TITLE
Improve UI of Contact Us Section

### ISSUE THREAD

**Issue by aanchal-fatwani** [Git21221/IBMSkillsBuild#34]
@Git21221 As part of HacktoberFest2023, I wish to update the UI of the Contact Us section for better presentation.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

![image](https://github.com/Git21221/IBMSkillsBuild/assets/63228776/53d8f541-6eeb-4723-b753-a77abb08d5b5)

**Comment by Git21221** [comment]
Hii @aanchal-fatwani , Thanks for raising a issue, 
Could you add b&w svg instead of that colorful image? It would be better....

**Comment by RABBI31** [comment]
Hello ,
I saw the issue and i think i can contribute it. If possible you can assign me the issue.
Thank you
