### ISSUE TITLE
Rocket icon on Projects page bugged.

### ISSUE THREAD

**Issue by Abh1noob** [Git21221/IBMSkillsBuild#36]
**Description**
Clicking Rocket Icon on 'Planets' page doesn't move up. Instead it gets locked on footer

**To Reproduce**
1. Go to 'Planets' on navbar
2. Click on 'rocket icon'

**Expected behavior**
- Move to top of screen

**What happens**
- Locked to footer

**Screenshots**
Scroll-up is not working.

<img width="1440" alt="image" src="https://github.com/Git21221/IBMSkillsBuild/assets/56132559/c3896791-88ff-482a-9275-8c12f4c68308">

**Desktop:**
 - OS: MacOS Ventura 13.4.1 (c)
 - Browser: Brave 1.58.135 Chromium: 117.0.5938.140 (Official Build) (arm64)

**Comment by Git21221** [comment]
@Abh1noob sure go ahead, make sure to make a pr with proper screenshot.
