### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by Kritika30032002** [Git21221/IBMSkillsBuild#43]
**Describe the bug**
Navbar drawer is not opening on mobile screens.
In Tablet view, It is not aligned properly.
assign this to me

**To Reproduce**

**Expected behavior**
Navbar drawer is  opening on mobile screens.
In Tablet view, It is aligned properly as desired.

**Screenshots**

![Screenshot (34104)](https://github.com/Git21221/IBMSkillsBuild/assets/83400697/aa658c49-4bc1-40a5-b4c3-ab7124c6f86e)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - windows
 - Browser [e.g. chrome, safari] - chrome
 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Git21221** [comment]
@Kritika30032002 sure go ahead, Make a pr with proper screenshot
