### ISSUE TITLE
spelling-error

### ISSUE THREAD

**Issue by Vatsalmadhur** [Git21221/IBMSkillsBuild#44]
**Describe the bug**
The button for sign-in should be documented as "Sign-In" and not as "sign".

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vatsalmadhur** [comment]
I request you to assign me this issue

**Comment by Git21221** [comment]
@Vatsalmadhur sure go ahead, Make a pr with proper screenshot

**Comment by Vatsalmadhur** [comment]
Hav a look at pr #58
