### ISSUE TITLE
Enhance the planet page UI

### ISSUE THREAD

**Issue by DivyanshiNarang** [Git21221/IBMSkillsBuild#49]
**Describe the bug**
Planets' image and buttons are not spaced properly

**Expected behavior**
There should be some margin between planet image and buttons

**Screenshots**
![image](https://github.com/Git21221/IBMSkillsBuild/assets/74779601/e10aa78b-12ce-4087-b2e2-561d3952b047)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [echrome]

**Comment by anjaliasha123** [comment]
Please assign this issue to me. I can add a margin: 6% 0 for .bar element
![image](https://github.com/Git21221/IBMSkillsBuild/assets/66244077/e1fe5fa2-6feb-4066-9bd9-b3dd55974554)

**Comment by Git21221** [comment]
@DivyanshiNarang sure go ahead, Make a pr with proper screenshot
