### ISSUE TITLE
Gallery UI - Card Image Fix

### ISSUE THREAD

**Issue by anjaliasha123** [Git21221/IBMSkillsBuild#50]
**Describe the bug**
The images in the cards in Gallery are not aligned properly. Some images appear to be shifted up.

![image](https://github.com/Git21221/IBMSkillsBuild/assets/66244077/9ffe7253-3545-4f41-aa35-17772ca5ac21)

**Desktop:**
 - OS: Windows
 - Browser: Chrome

**Additional context**
With CSS change the acrds in the Gallery can be displayed as shown below:
![image](https://github.com/Git21221/IBMSkillsBuild/assets/66244077/f0b49572-0de0-4865-9f38-051310a37ade)

**Comment by anjaliasha123** [comment]
Please assign this issue to me 😃!

**Comment by Git21221** [comment]
@anjaliasha123 sure go ahead, Make a pr with proper screenshot

**Comment by anjaliasha123** [comment]
Fixed the issue
