### ISSUE TITLE
More About Space - Read More Button Issue

### ISSUE THREAD

**Issue by anjaliasha123** [Git21221/IBMSkillsBuild#51]
**Describe the bug**
In the home page, More About Space seaction cards button does not redirect to any page on clicking
![image](https://github.com/Git21221/IBMSkillsBuild/assets/66244077/89a48946-e488-4c1f-9193-f24a809a2236)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Solution: Adding a tag with href pointing to planets/planets.html#iss & planets/planets.html#asteroid for the respective Read More buttons

**Comment by anjaliasha123** [comment]
Please assign this issue to me 😃!

**Comment by Git21221** [comment]
@anjaliasha123 sure go ahead, Make a pr with proper screenshot

**Comment by anjaliasha123** [comment]
Fixed the issue

**Comment by anjaliasha123** [comment]
I am closing this issue. Thank you for accepting the PR #52
