### ISSUE TITLE
sign up page profile upload profile pic is accepting all type of formate

### ISSUE THREAD

**Issue by ozasatyam** [Git21221/IBMSkillsBuild#53]
**Describe the bug**
In the sign up page we can upalod any type of file(even non image)

**To Reproduce**
1. Go to 'https://virtual-galaxy.netlify.app/ui/register'
2. Click on 'profile photo'
3. upload any type like ppt, word excel and allowing it

**Expected behavior**
it's allow only image type(jpg png gif)

**Comment by Git21221** [comment]
@ozasatyam sure go ahead, Make a pr with proper screenshot
