### ISSUE TITLE
SOLAR SYSTEM

### ISSUE THREAD

**Issue by Durgesh4993** [Git21221/IBMSkillsBuild#55]
ScreenShot:

![image](https://github.com/Git21221/IBMSkillsBuild/assets/98798977/17a48539-093b-43cf-8df2-f3498548b1a8)

Demo vedio:

https://github.com/Git21221/IBMSkillsBuild/assets/98798977/41a54476-ec01-47fd-943b-a358c2e163a3

**Comment by Git21221** [comment]
In which section do you want to add this? @Durgesh4993

**Comment by Durgesh4993** [comment]
@Git21221 As you suggest

**Comment by Git21221** [comment]
@Durgesh4993 ok do one thing, 
![image](https://github.com/Git21221/IBMSkillsBuild/assets/101005577/60e129e2-0f3f-4003-a011-20cf077ae325)
in this part add yours....match the font style and "solar system" will be at the to of it and some text will be bottom of it.
Have any confusion -> mention me.
