### ISSUE TITLE
[BUG] [Privacy Policy] missing 'Privacy Policy' page

### ISSUE THREAD

**Issue by bugITwhisperer** [Git21221/IBMSkillsBuild#59]
**Description**
Privacy Policy info is missing.

**Steps to reproduce**
1. Go to 'https://virtual-galaxy.netlify.app/faq/faq#'
2. Scroll down to the bottom of the page
3. Under 'Useful Links' - click on 'Privacy Policy' in the footer
4. Observe: 404NotFound error && URL name is the same as for 'Privacy Policy' and should be adjusted

**Expected Results**
Privacy Policy page should be displayed.

**Actual Results**
Instead of Privacy Policy info, there is a 404 "not found" error displayed:
![2023-10-02_18h20_47](https://github.com/Git21221/IBMSkillsBuild/assets/97608493/cddcbe20-fae0-4f67-a99c-33dd3efceef0)

---
Could you provide more information about the privacy policy page? What would you like the page to include?
And please assign me to this issue, so I can fix this :)

**Comment by Git21221** [comment]
@bugITwhisperer Do according to your choice. If you need any help regarding rules @RAHUL956777 can help you.

**Comment by bugITwhisperer** [comment]
@Git21221: I believe this issue can be marked as completed since the PR has been already merged.
