### ISSUE TITLE
[BUG] [Terms of service] missing 'Terms of service' page, incorrect URL name

### ISSUE THREAD

**Issue by bugITwhisperer** [Git21221/IBMSkillsBuild#60]
**Description**
'Terms of service' info is missing.

**Steps to reproduce**
1. Go to 'https://virtual-galaxy.netlify.app/faq/faq#'
2. Scroll down to the bottom of the page
3. Under 'Useful Links' - click on 'Terms of service' in the footer
4. Observe: 404NotFound error && URL name is the same as for 'Privacy Policy' and should be adjusted

**Expected Results**
Terms of service page should be displayed.

**Actual Results**
Instead of Terms of service info, there is a 404 "not found" error displayed:
![image](https://github.com/Git21221/IBMSkillsBuild/assets/97608493/5a610f68-48fd-4914-9d66-f5ad7399c430)
![image](https://github.com/Git21221/IBMSkillsBuild/assets/97608493/6cd2c2ad-d8c5-40ee-83b1-801abf65e795)

---
Could you provide more information about the 'Terms of service' page? What would you like the page to include?
And please assign me to this issue, so I can fix this :)

**Comment by Git21221** [comment]
@bugITwhisperer Do according to your choice. If you need any help regarding rules @RAHUL956777 can help you.

**Comment by bugITwhisperer** [comment]
@RAHUL956777 : can you advise on the rules that should be included on the page please?:)

**Comment by RAHUL956777** [comment]
Privacy Policy
 @bugITwhisperer here is a demo ...feel free to change it according to you
04-10-2023

Introduction

Welcome to virtual galaxy . We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our website . By accessing or using the Service, you consent to the practices described in this Privacy Policy.

**Information We Collect**

We may collect the following types of information:

Personal Information: we can use your personal information like your name and email for our further services.

Device Information: we cannot use your device information like ip..or other device informarion
Usage Data: 

**How We Use Your Information**

We may use your information for the following purposes:

[List the specific purposes, such as providing services, improving user experience, sending newsletters, etc.]
Data Sharing

We may share your information with the following third parties:

[List third-party services or partners you share data with, and explain why and how.]
Cookies and Tracking Technologies

We use cookies and similar tracking technologies. By using the Service, you consent to the use of cookies.

User Rights

You have the right to:

Access your personal information.
Correct inaccuracies in your personal information.
Delete your personal information.
Object to the processing of your personal information.
Security

We implement reasonable security measures to protect your information from unauthorized access or breaches.

Data Retention

We retain your information for as long as necessary for the purposes outlined in this Privacy Policy.

Legal Basis

[Explain the legal basis for processing user data, if applicable.]

International Data Transfers

[Explain how international data transfers are handled, if applicable.]

Updates to the Policy

We may update this Privacy Policy periodically. Changes will be posted on this page, and the date of the latest revision will be indicated.

Contact Information

If you have any questions or concerns about this Privacy Policy, please contact us at [contact email].

**Comment by bugITwhisperer** [comment]
@RAHUL956777 : Thanks so much for the details, Rahul! I'm on it! :)

**Comment by bugITwhisperer** [comment]
One more question @RAHUL956777 - do you want me to remove the 'Terms of service' from the footer? And just leave out 'Privacy Policy' page to avoid content's duplication? 

Or do you prefer to split the contents into 2 separate pages: 
- 'Privacy Policy'
- 'Terms of service'
as we currently can see in the footer:
![image](https://github.com/Git21221/IBMSkillsBuild/assets/97608493/1ef1b43d-eb08-47e8-bf52-4855651906c2)

**Comment by RAHUL956777** [comment]
@bugITwhisperer ok remove it ..

**Comment by bugITwhisperer** [comment]
@Git21221: I believe this issue can be marked as completed since the PR has been already merged.
