### ISSUE TITLE
Planets section bug

### ISSUE THREAD

**Issue by Git21221** [Git21221/IBMSkillsBuild#66]
![image](https://github.com/Git21221/IBMSkillsBuild/assets/101005577/95ae1dee-15aa-450f-98ca-73981c5af72b)
## This part should be here but somehow it is not there....please fix this bug
![image](https://github.com/Git21221/IBMSkillsBuild/assets/101005577/deda30df-a828-4d39-9033-888f6fc0267c)

**Comment by anjaliasha123** [comment]
Seems the display property is set to none.
![image](https://github.com/Git21221/IBMSkillsBuild/assets/66244077/32cd9b8f-7732-42e0-9d71-e56390447a1b)

**Comment by Git21221** [comment]
@anjaliasha123 sure go ahead, make a pr

**Comment by anjaliasha123** [comment]
Raised a PR. Kindly review
