### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by zainbinshakoor** [Git21221/IBMSkillsBuild#69]
![image](https://github.com/Git21221/IBMSkillsBuild/assets/92578770/c0250f2a-c4d0-4826-a9b0-97d6186152ed)
Make a detail page or may be popup that display the complete info related to this item @Git21221

**Comment by Git21221** [comment]
@zainbinshakoor sure go ahead, make a pr with proper rules #68

**Comment by zainbinshakoor** [comment]
@Git21221 sure

**Comment by zainbinshakoor** [comment]
- #71
